name: DoubleJump
version: '${project.version}'
main: me.fivevl.doublejump.Main
api-version: 1.18
authors: [ 5vl ]
description: A trial project for DevRoom.
commands:
  jumpmenu:
    description: Opens the main jump GUI